// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5athveWKq0RsdEvpCPovtU5K-eiYo9yU',
    appId: '1:216028398366:web:62dd78c053e0677fb17f0f',
    messagingSenderId: '216028398366',
    projectId: 'taskmanager-d08f9',
    authDomain: 'taskmanager-d08f9.firebaseapp.com',
    storageBucket: 'taskmanager-d08f9.firebasestorage.app',
    measurementId: 'G-ST669RHX8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6n4rp3Y8LXfvzoqKydvmoAjH4TSX_5Ng',
    appId: '1:216028398366:android:ea07314be37b5e62b17f0f',
    messagingSenderId: '216028398366',
    projectId: 'taskmanager-d08f9',
    storageBucket: 'taskmanager-d08f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQXKubXG0Bs5yX_QvtiN6c8CAkCwm6QQ',
    appId: '1:216028398366:ios:231bc164f10c6dc0b17f0f',
    messagingSenderId: '216028398366',
    projectId: 'taskmanager-d08f9',
    storageBucket: 'taskmanager-d08f9.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagenet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQXKubXG0Bs5yX_QvtiN6c8CAkCwm6QQ',
    appId: '1:216028398366:ios:231bc164f10c6dc0b17f0f',
    messagingSenderId: '216028398366',
    projectId: 'taskmanager-d08f9',
    storageBucket: 'taskmanager-d08f9.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagenet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5athveWKq0RsdEvpCPovtU5K-eiYo9yU',
    appId: '1:216028398366:web:51231887a97da69fb17f0f',
    messagingSenderId: '216028398366',
    projectId: 'taskmanager-d08f9',
    authDomain: 'taskmanager-d08f9.firebaseapp.com',
    storageBucket: 'taskmanager-d08f9.firebasestorage.app',
    measurementId: 'G-6LNVL14LCH',
  );
}
